import { test, expect } from "@playwright/test";
import { AuctionListPage } from "../../../pages/backoffice/AuctionListPage";
import { BidAuctionFormPage } from "../../../pages/backoffice/BidAuctionFormPage";
import { generateBidAuctionData } from "../../../fixtures/bid-auction-data";
import { saveState } from "../../../fixtures/test-state";

test.describe("Auction - Auction List > Add Bid Auction", () => {
  test.describe.configure({ mode: "serial" });

  test("OAA-001: clicking Add Auction navigates to the bid auction form", async ({ page }) => {
    const list = new AuctionListPage(page);

    await test.step("Given I am on the Open House Auction list", async () => {
      await list.goto();
      await list.clickOpenHouseTab();
    });

    await test.step("When I click the Add Auction button", async () => {
      await list.clickAddAuction();
    });

    await test.step("Then I should see the Add Bid Auction page", async () => {
      await expect(page.locator("h1, h2, h3").filter({ hasText: "Add Bid Auction" }).first()).toBeVisible();
    });

    await test.step("And the Bid Auction Data section should be visible", async () => {
      await expect(page.getByText("Bid Auction Data")).toBeVisible();
    });
  });

  test("OAA-002: add bid auction form has all required fields", async ({ page }) => {
    const list = new AuctionListPage(page);

    await test.step("Given I navigate to the Add Bid Auction page", async () => {
      await list.goto();
      await list.clickOpenHouseTab();
      await list.clickAddAuction();
    });

    const form = new BidAuctionFormPage(page);

    await test.step("Then the Location dropdown should be visible", async () => {
      await expect(form.locationSelect).toBeVisible();
    });

    await test.step("And the Auction No field should be visible", async () => {
      await expect(form.auctionNoInput).toBeVisible();
    });

    await test.step("And the Start and End datetime fields should be visible", async () => {
      await expect(form.startInput).toBeVisible();
      await expect(form.endInput).toBeVisible();
    });

    await test.step("And the vehicle table should be visible with expected columns", async () => {
      await expect(form.vehicleTable).toBeVisible();
      const headers = await form.getVehicleTableHeaders();
      expect(headers).toEqual(
        expect.arrayContaining(["Vehicle Control No.", "Model", "Plate Number", "Seller Name", "Start Price"])
      );
    });
  });

  test("OAA-003: fill bid auction form with valid data", async ({ page }) => {
    test.setTimeout(60000);
    const bidData = generateBidAuctionData("JBAP");

    const list = new AuctionListPage(page);

    await test.step("Given I navigate to the Add Bid Auction page", async () => {
      await list.goto();
      await list.clickOpenHouseTab();
      await list.clickAddAuction();
    });

    const form = new BidAuctionFormPage(page);

    await test.step("When I fill Location, Start and End datetime", async () => {
      await form.fillForm(bidData);
      await page.waitForTimeout(1000);
    });

    await test.step("Then Auction No should be auto-generated by the server", async () => {
      const values = await form.getFormValues();
      expect(values.auctionNo).toBeTruthy();
      expect(Number(values.auctionNo)).toBeGreaterThan(0);
    });

    await test.step("And Start and End datetime should have the correct values", async () => {
      const values = await form.getFormValues();
      expect(values.startDateTime).toBe(bidData.startDateTime);
      expect(values.endDateTime).toBe(bidData.endDateTime);
    });

    await test.step("And I save the bid auction data for subsequent tests", async () => {
      const values = await form.getFormValues();
      saveState({
        bidAuctionNo: values.auctionNo,
        bidAuctionStart: values.startDateTime,
        bidAuctionEnd: values.endDateTime,
      });
    });
  });

  test("OAA-004: search seller and select vehicle", async ({ page }) => {
    test.setTimeout(90000);
    const bidData = generateBidAuctionData("JBAP");

    const list = new AuctionListPage(page);

    await test.step("Given I navigate to the Add Bid Auction page and fill form", async () => {
      await list.goto();
      await list.clickOpenHouseTab();
      await list.clickAddAuction();
    });

    const form = new BidAuctionFormPage(page);

    await test.step("And I fill Location, Start and End datetime", async () => {
      await form.fillForm(bidData);
      await page.waitForTimeout(1000);
    });

    await test.step("When I search for seller 'ABI SELLER TAN'", async () => {
      await form.searchSeller("ABI SELLER TAN");
    });

    await test.step("Then vehicles should appear in the table", async () => {
      const rowCount = await form.getVehicleRowCount();
      expect(rowCount).toBeGreaterThan(0);
    });

    await test.step("When I select all vehicles and fill Lot No for each", async () => {
      await form.selectAllVehicles();
    });

    await test.step("And I click Next", async () => {
      await form.clickNext();
    });

    await test.step("Then the page should proceed to the confirmation step", async () => {
      await expect(form.saveButton).toBeVisible({ timeout: 10000 });
    });

    await test.step("When I click Save", async () => {
      await form.saveButton.click();
      await page.waitForTimeout(3000);
    });

    await test.step("Then a success message should appear", async () => {
      await expect(page.locator(".swal2-title")).toHaveText("Success", { timeout: 10000 });
    });

    await test.step("When I click Ok on the success dialog", async () => {
      await page.locator(".swal2-confirm").click();
      await page.waitForLoadState("networkidle");
      await page.waitForTimeout(2000);
    });
  });
});
